version: '3.8'

services:
  twitter-api:
    build: .
    container_name: twitter-api
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - ./db.sqlite:/usr/src/app/db.sqlite
      - ./accounts.json:/usr/src/app/accounts.json:ro
      - ./logs:/usr/src/app/logs
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:${PORT}/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3 